spring.application.name=EndWork
spring.datasource.url=jdbc:mysql://localhost:3306/javaclass
spring.datasource.username=$$$
spring.datasource.password=$$$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jackson.time-zone=Asia/Shanghai
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss